-- Apply once to a new Supabase project using the SQL editor.
create sequence public.incident_number start 1001;
create table public.profiles(id uuid primary key references auth.users on delete cascade,name text not null,email text,role text not null default 'citizen' check(role in ('citizen','authority','worker')));
create function public.civic_role() returns text language sql stable security definer set search_path=public as $$ select role from profiles where id=auth.uid() $$;
create function public.create_profile() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,name,email,role) values(new.id,coalesce(new.raw_user_meta_data->>'name','Citizen'),new.email,'citizen');return new;end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.create_profile();
insert into profiles(id,name,email) select id,coalesce(raw_user_meta_data->>'name','Citizen'),email from auth.users on conflict do nothing;
create table public.incidents(id text primary key default ('CIV-'||nextval('public.incident_number')),issue_type text not null check(issue_type in ('Pothole','Garbage','Waterlogging')),latitude double precision not null check(latitude between -90 and 90),longitude double precision not null check(longitude between -180 and 180),address text not null check(length(address) between 1 and 300),severity text not null check(severity in ('LOW','MEDIUM','HIGH')),importance text not null check(importance in ('residential','main road','school','hospital','market')),priority text not null default 'MEDIUM',confidence double precision not null check(confidence between 0 and 1),department text not null,status text not null default 'Pending',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.incident_reports(id uuid primary key default gen_random_uuid(),incident_id text not null references incidents,user_id uuid not null references profiles,image_url text,created_at timestamptz not null default now(),unique(incident_id,user_id));
create table public.assignments(id uuid primary key default gen_random_uuid(),incident_id text not null unique references incidents,worker_id uuid not null references profiles,assigned_at timestamptz not null default now(),status text not null default 'Assigned',completed_at timestamptz);
create table public.status_history(id uuid primary key default gen_random_uuid(),incident_id text not null references incidents,status text not null,actor_id uuid references profiles,created_at timestamptz not null default now());
create table public.analysis_results(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles,incident_id text references incidents,issue_type text not null,severity text not null,confidence double precision not null,explanation text not null,verified boolean not null default false,same_scene boolean not null default false,image_hash text not null,image_url text not null,created_at timestamptz not null default now());
create table public.verification(id uuid primary key default gen_random_uuid(),incident_id text not null references incidents,before_image_url text,after_image_url text not null,ai_result jsonb not null,verified boolean not null,created_at timestamptz not null default now());
create index incidents_status_idx on incidents(status,created_at);
create index incidents_location_idx on incidents(issue_type,latitude,longitude);
create index status_history_incident_idx on status_history(incident_id,created_at);
alter table profiles enable row level security;alter table incidents enable row level security;alter table incident_reports enable row level security;alter table assignments enable row level security;alter table status_history enable row level security;alter table analysis_results enable row level security;alter table verification enable row level security;
create policy profiles_read on profiles for select to authenticated using(id=auth.uid() or civic_role()='authority');
create policy incidents_read on incidents for select to authenticated using(true);
create policy reports_read on incident_reports for select to authenticated using(user_id=auth.uid() or civic_role()='authority');
create policy assignments_read on assignments for select to authenticated using(worker_id=auth.uid() or civic_role()='authority');
create policy history_read on status_history for select to authenticated using(true);
create policy analyses_read on analysis_results for select to authenticated using(user_id=auth.uid());
create policy verification_read on verification for select to authenticated using(true);
-- No client INSERT/UPDATE/DELETE policies: all changes pass through validated RPCs.
create function public.priority_level(p_severity text,p_importance text,p_reports integer,p_created timestamptz) returns text language sql stable as $$ select case when score>=80 then 'CRITICAL' when score>=60 then 'HIGH' when score>=35 then 'MEDIUM' else 'LOW' end from (select round((case p_severity when 'HIGH' then 45 when 'MEDIUM' then 30 else 15 end)+(case p_importance when 'hospital' then 25 when 'school' then 20 when 'main road' then 15 when 'market' then 10 else 0 end)+least(20,p_reports*1.2)+least(10,greatest(0,extract(epoch from(now()-p_created))/10800))) score) s $$;
-- Count reports without exposing other citizens' identity.
create function public.report_count(p_id text) returns integer language sql stable security definer set search_path=public as $$select count(*)::integer from incident_reports where incident_id=p_id$$;
create view public.incident_view with(security_invoker=true) as select i.*,public.report_count(i.id) reports,exists(select 1 from incident_reports r where r.incident_id=i.id and r.user_id=auth.uid()) mine,(select r.image_url from incident_reports r where r.incident_id=i.id order by r.created_at limit 1) image_url,a.worker_id,a.assigned_at,v.after_image_url,v.ai_result->>'explanation' verification_explanation,(select jsonb_agg(jsonb_build_object('status',h.status,'created_at',h.created_at) order by h.created_at) from status_history h where h.incident_id=i.id) history from incidents i left join assignments a on a.incident_id=i.id left join lateral(select * from verification where incident_id=i.id order by created_at desc limit 1) v on true;
create function public.validate_evidence(p_url text) returns void language plpgsql security definer set search_path=public as $$begin if auth.uid() is null or p_url is null or p_url not like '%/storage/v1/object/public/incident-images/'||auth.uid()::text||'/%' then raise exception 'Evidence must be uploaded by the signed-in user';end if;end$$;
create function public.submit_incident(p_analysis_id uuid,p_lat double precision,p_lng double precision,p_address text,p_importance text,p_image text,p_duplicate text default null) returns text language plpgsql security definer set search_path=public as $$declare a analysis_results; n text; i incidents;begin
if civic_role() not in ('citizen','authority') then raise exception 'Citizen or authority account required';end if;
select * into a from analysis_results where id=p_analysis_id and user_id=auth.uid() and incident_id is null and created_at>now()-interval '1 hour';if not found or a.issue_type='None' then raise exception 'Valid recent detection required';end if;
if a.image_url<>p_image then raise exception 'Evidence must match the analyzed image';end if;perform validate_evidence(p_image);if p_importance not in ('residential','main road','school','hospital','market') then raise exception 'Invalid importance';end if;
if p_duplicate is not null then select * into i from incidents where id=p_duplicate for update;if not found or i.issue_type<>a.issue_type or i.status in ('Resolved','Rejected') or i.created_at<now()-interval '7 days' or sqrt(power((i.latitude-p_lat)*111320,2)+power((i.longitude-p_lng)*111320*cos(radians(p_lat)),2))>40 then raise exception 'This is not a nearby matching incident';end if;n=i.id;
else insert into incidents(issue_type,latitude,longitude,address,severity,importance,confidence,department,status) values(a.issue_type,p_lat,p_lng,trim(p_address),a.severity,p_importance,a.confidence,case a.issue_type when 'Pothole' then 'Road Maintenance' when 'Garbage' then 'Waste Management' else 'Drainage' end,case when a.confidence<.7 then 'Review Required' else 'Pending' end) returning id into n;end if;
insert into incident_reports(incident_id,user_id,image_url) values(n,auth.uid(),p_image);insert into status_history(incident_id,status,actor_id) values(n,case when p_duplicate is null then 'Reported' else 'Citizen confirmed same issue' end,auth.uid());update incidents set priority=priority_level(severity,importance,report_count(n),created_at),updated_at=now() where id=n;return n;end$$;
create function public.incident_action(p_id text,p_action text,p_value text default null) returns void language plpgsql security definer set search_path=public as $$declare i incidents;w uuid;nstatus text;begin
select * into i from incidents where id=p_id for update;if not found then raise exception 'Incident not found';end if;
if p_action='support' then if civic_role()<>'citizen' or i.status in ('Resolved','Rejected') then raise exception 'Cannot confirm this issue';end if;insert into incident_reports(incident_id,user_id) values(p_id,auth.uid());nstatus='Citizen confirmed same issue';
elsif civic_role()='authority' then
case p_action when 'assign' then if i.status in ('Resolved','Rejected') then raise exception 'Incident closed';end if;w=p_value::uuid;if not exists(select 1 from profiles where id=w and role='worker') then raise exception 'Worker profile required';end if;insert into assignments(incident_id,worker_id,status) values(p_id,w,'Assigned') on conflict(incident_id) do update set worker_id=w,status='Assigned',assigned_at=now(),completed_at=null;update incidents set status='Assigned' where id=p_id;nstatus='Assigned';
when 'department' then if p_value not in ('Road Maintenance','Waste Management','Drainage') then raise exception 'Invalid department';end if;update incidents set department=p_value where id=p_id;nstatus='Department changed to '||p_value;
when 'review' then update incidents set status='Review Required' where id=p_id;nstatus='Review Required';
when 'reject' then update incidents set status='Rejected' where id=p_id;nstatus='Rejected';
when 'approve' then if not exists(select 1 from verification where incident_id=p_id) or i.status<>'Review Required' then raise exception 'Completion evidence under review required';end if;update incidents set status='Resolved' where id=p_id;update assignments set status='Completed',completed_at=now() where incident_id=p_id;nstatus='Resolved — authority approved after visual review';
else raise exception 'Unknown action';end case;
elsif civic_role()='worker' and p_action='status' then
if not exists(select 1 from assignments where incident_id=p_id and worker_id=auth.uid()) then raise exception 'This task is not assigned to you';end if;
if not((i.status='Assigned' and p_value='Accepted')or(i.status='Accepted' and p_value='En Route')or(i.status='En Route' and p_value='On Site')or(i.status='On Site' and p_value='In Progress')) then raise exception 'Invalid task transition';end if;update incidents set status=p_value where id=p_id;update assignments set status=p_value where incident_id=p_id;nstatus=p_value;
else raise exception 'This role cannot perform this action';end if;
update incidents set priority=priority_level(severity,importance,report_count(p_id),created_at),updated_at=now() where id=p_id;insert into status_history(incident_id,status,actor_id) values(p_id,nstatus,auth.uid());end$$;
create function public.complete_incident(p_id text,p_analysis_id uuid,p_after text) returns void language plpgsql security definer set search_path=public as $$declare i incidents;a analysis_results;b text;passed boolean;begin
select * into i from incidents where id=p_id for update;if not found or i.status not in ('In Progress','Review Required') then raise exception 'An active repair is required';end if;
if civic_role()<>'worker' or not exists(select 1 from assignments where incident_id=p_id and worker_id=auth.uid()) then raise exception 'Assigned worker required';end if;
select * into a from analysis_results where id=p_analysis_id and user_id=auth.uid() and incident_id=p_id and created_at>now()-interval '1 hour';if not found then raise exception 'Recent verification of this incident required';end if;
if a.image_url<>p_after then raise exception 'Completion must match analyzed evidence';end if;perform validate_evidence(p_after);select image_url into b from incident_reports where incident_id=p_id and image_url is not null order by created_at limit 1;if b=p_after then raise exception 'A new after-repair photo is required';end if;
passed=a.verified and a.same_scene and a.confidence>=.7;insert into verification(incident_id,before_image_url,after_image_url,ai_result,verified) values(p_id,b,p_after,jsonb_build_object('explanation',a.explanation,'confidence',a.confidence,'same_scene',a.same_scene,'analysis_id',a.id),passed);update incidents set status=case when passed then 'Resolved' else 'Review Required' end,updated_at=now() where id=p_id;update assignments set status=case when passed then 'Completed' else 'Review Required' end,completed_at=case when passed then now() else null end where incident_id=p_id;insert into status_history(incident_id,status,actor_id) values(p_id,case when passed then 'Resolved' else 'Review Required' end,auth.uid());end$$;
revoke all on all tables in schema public from anon;grant select on profiles,incidents,incident_reports,assignments,status_history,analysis_results,verification,incident_view to authenticated;
revoke all on function submit_incident(uuid,double precision,double precision,text,text,text,text),incident_action(text,text,text),complete_incident(text,uuid,text),validate_evidence(text) from public;grant execute on function submit_incident(uuid,double precision,double precision,text,text,text,text),incident_action(text,text,text),complete_incident(text,uuid,text) to authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('incident-images','incident-images',true,10485760,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
create policy evidence_upload on storage.objects for insert to authenticated with check(bucket_id='incident-images' and (storage.foldername(name))[1]=auth.uid()::text);
create policy evidence_read on storage.objects for select to authenticated using(bucket_id='incident-images');
-- Promote trusted users using SQL editor only:
-- update public.profiles set role='authority' where email='your-authority@example.com';
-- update public.profiles set role='worker',name='Road Team A' where email='your-worker@example.com';


